ACIS_system_v1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

    path('programs/', include('Programs.urls', namespace='programs')), 
    path('dashboard/', include('Dashboard.urls', namespace='dashboards')),
    path('accreditation/', include('Accreditation.urls', namespace= 'accreditation')),
    path('user/', include('Users.urls', namespace ='users')),

    path('', include('LandingPage.urls', namespace = 'index')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('api/', include('Api.urls', namespace ='apis')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accreditation/urls.py
from django.urls import path
from Accreditation import  views_accreditation, views_accreditation_result, views_assign_user, views_instrument_folder, views_instrument_level, views_reports, views_submission_bin
from . import views_level, views_bodies, views_instrument

from Accreditation.views_instrument_level import *

app_name = 'accreditations'

urlpatterns = [

    #------------------------------[ URLS FOR ACCREDITATION LEVEL MODULE ]------------------------------#
    path("level/", views_level.landing_page, name='level-landing'),
    path("level/create/", views_level.create_level, name='level-create'),
    path("level/update/<str:pk>/", views_level.update_level, name='level-update'),
    path("level/archive/<str:pk>/", views_level.archive_level, name='level-archive'),
    path("level/archive_page/", views_level.archive_level_page, name='level-archive-page'),
    path("level/archive_page/restore/<str:pk>/", views_level.restore_level, name='level-archive-page-restore'),
    path("level/archive_page/destroy/<str:pk>/", views_level.destroy_level, name='level-archive-page-destroy'),

    
    #------------------------------[ URLS FOR ACCREDITATION BODIES MODULE ]------------------------------#
    path("bodies/", views_bodies.landing_page, name='bodies-landing'),
    path("bodies/create/", views_bodies.create_bodies, name='bodies-create'),
    path("bodies/update/<str:pk>/", views_bodies.update_bodies, name='bodies-update'),
    path("bodies/archive/<str:pk>/", views_bodies.archive_bodies, name='bodies-archive'),
    path("bodies/archive_page/", views_bodies.archive_landing, name='bodies-archive-page'),
    path("bodies/archive_page/restore/<str:pk>/", views_bodies.restore_bodies, name='bodies-archive-page-restore'),
    path("bodies/archive_page/destroy/<str:pk>/", views_bodies.destroy_bodies, name='bodies-archive-page-destroy'),
    
    #------------------------------[ URLS FOR INSTRUMENT MODULE]------------------------------#
    path("instrument/", views_instrument.InstrumentList.as_view(), name='instrument-list'),
    path("instrument/update/<str:pk>/", views_instrument.update, name='instrument-update'),
    path("instrument/archive/<str:pk>/", views_instrument.archive, name='instrument-archive'),
    path("instrument/archive_page/", views_instrument.archive_landing, name='instrument-archive-page'),
    path("instrument/archive_page/restore/<str:pk>/", views_instrument.restore, name='instrument-restore'),
    path("instrument/archive_page/destroy/<str:pk>/", views_instrument.destroy, name='instrument-destroy'),

    #------------------------------[ URLS FOR INSTRUMENT LEVEL ]------------------------------#
    path("instrument/level/<str:pk>/", InstrumentLevelList.as_view(), name='instrument-level'),
    path("instrument/level/create/<int:pk>/", InstrumentLevelList.as_view(), name='instrument-level-create'),
    path("instrument/level/update/<str:pk>/", views_instrument_level.update, name='instrument-level-update'),
    path("instrument/level/archive/<str:ins_pk>/<str:pk>/", views_instrument_level.archive, name='instrument-level-archive'),
    path("instrument/level/<str:pk>/archive-page/", views_instrument_level.archive_landing, name='instrument-level-archive-page'),
    path("instrument/level/archive-page/restore/<str:ins_pk>/<str:pk>/", views_instrument_level.restore, name='instrument-level-restore'),
    path("instrument/level/archive-page/destroy/<str:pk>/", views_instrument_level.destroy, name='instrument-level-destroy'),

    #------------------------------[ URLS FOR PARENT FOLDER ]------------------------------#
    path("instrument/level/directory/<str:pk>/", views_instrument_folder.parent_landing_page, name='instrument-level-directory'),
    path("instrument/level/directory/create/<str:pk>/", views_instrument_folder.create, name='instrument-directory-create'),
    path("instrument/level/directory/update/<str:pk>/", views_instrument_folder.update, name='instrument-directory-update'),
    path("instrument/level/directory/archive/<str:pk>/<str:level_id>/", views_instrument_folder.archive, name='instrument-directory-archive'),
    path("instrument/level/parent-directory/file/archive/<str:pk>/", views_instrument_folder.archive_files, name='parent-directory-file-archive'),
    path("instrument/level/parent-directory/recycle-bin/<str:pk>/", views_instrument_folder.parent_recycle_bin, name='parent-folder-recycle-bin'),
    path("instrument/level/parent-directory/recycle-bin/restore/<str:ins_pk>/<str:pk>/", views_instrument_folder.restore_parent, name='parent-directory-recycle-bin-restore'),
    path("instrument/level/parent-directory/recycle-bin/destroy/<str:pk>/", views_instrument_level.destroy, name='parent-directory-recycle-bin-destroy'),
    path("instrument/level/parent-directory/upload-files/<str:pk>/", views_submission_bin.create_parent_folder_files, name='parent-folder-files-upload'),
    path("instrument/level/directory/recycle-bin/destroy/<str:pk>/", views_instrument_folder.destroy, name='folder-destroy'),


    #------------------------------[ URLS FOR CHILD FOLDER ]------------------------------#
    path("instrument/level/child/directory/<str:pk>/", views_instrument_folder.child_landing_page, name='instrument-level-child-directory'),
    path("instrument/level/child/directory/create/<str:pk>/", views_instrument_folder.create_child, name='instrument-directory-create-child'),
    path("instrument/level/child/directory/archive/<str:pk>/<str:parent_id>/", views_instrument_folder.archive_child, name='instrument-directory-archive-child'),
    path("instrument/level/child-directory/recycle-bin/<str:pk>/", views_instrument_folder.child_recycle_bin, name='child-folder-recycle-bin'),
    path("instrument/level/child-directory/recycle-bin/restore/<str:parent_pk>/<str:pk>/", views_instrument_folder.restore_child, name='child-directory-recycle-bin-restore'),
    path("instrument/level/child-directory/recycle-bin/restore-file/<str:pk>/", views_instrument_folder.restore_child_file, name='child-file-restore'),
    path("instrument/level/child-directory/upload-files/<str:pk>/", views_submission_bin.create_child_folder_files, name='child-folder-files-upload'),


    #------------------------------[ URLS FOR SUBMISSION BIN ]------------------------------#
    path("instrument/level/directory/submission-bin/<str:pk>/", views_submission_bin.landing_page, name='submission-bin-page'),
    path("instrument/level/parent-directory/create/submission-bin/<str:pk>/", views_submission_bin.create_submissionBin_parent, name='create-parent-submission-bin'),
    path("instrument/level/child-directory/create/submission-bin/<str:pk>/", views_submission_bin.create_submissionBin_child, name='create-child-submission-bin'),
    path("instrument/level/directory/submission-bin/update/<str:pk>/", views_submission_bin.update, name='instrument-directory-update'),
    path("instrument/level/directory/submission-bin/upload-files/<str:pk>/", views_submission_bin.create_files, name='files-upload'),
    path("instrument/level/directory/submission-bin/archive/<str:pk>/<str:bin_id>/", views_submission_bin.archive, name='file-archive'),
    path("instrument/level/directory/submission-bin/recycle-bin/<str:pk>/", views_submission_bin.recycle_bin, name='submission-bin-recycle-bin-page'),
    path("instrument/level/directory/submission-bin/recycle-bin/restore/<str:pk>/", views_submission_bin.restore, name='file-restore'),
    path("instrument/level/directory/submission-bin/recycle-bin/destroy/<str:pk>/", views_submission_bin.destroy, name='file-destroy'),
    path("submission-bin/file/change/reviewable/<str:pk>/", views_submission_bin.change_to_reviewable_file, name='submission-bin-change-to-reviewable'),
    path("submission-bin/file/change/unreviewable/<str:pk>/", views_submission_bin.change_to_not_reviewable_file, name='submission-bin-change-to-unreviewable'),


    #------------------------------[ URLS FOR PROGRAM ACCREDITATION ]------------------------------#
    path("filter-instrument-option/", views_accreditation.filter_instrument, name='filter-instument-option'),

    path("", views_accreditation.landing_page, name='landing'),
    path("create/", views_accreditation.create, name='accreditation-create'),
    path("update/<str:pk>/", views_accreditation.update, name='accreditation-update'),
    path("archive/<str:pk>/", views_accreditation.archive, name='accreditation-archive'),
    path("archive-page/", views_accreditation.archive_landing, name='accreditation-archive-page'),
    path("archive-page/restore/<str:pk>/", views_accreditation.restore, name='accreditation-restore'),
    path("archive-page/destroy/<str:pk>/", views_accreditation.destroy, name='accreditation-destroy'),


    #------------------------------[ URLS FOR ASSIGNING USER TO A FOLDER ]------------------------------#
    path("directory/assign-user/", views_assign_user.assign_user, name='folder-assign-user'),
    path("directory/assign-user/chairman/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_chairman, name='folder-assign-user-chairman'),   
    path("directory/assign-user/co-chairman/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_cochariman, name='folder-assign-user-cochairman'),
    path("directory/assign-user/member/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_member, name='folder-assign-user-member'),
    path("directory/assign-user/remove-user/<str:pk>/<str:folder_pk>/", views_assign_user.removed_user_to_folder, name='folder-remove-user'),


    #------------------------------[ URLS FOR REVIEWING FILES AND FOLDERS ]------------------------------#
    path("create-review/<str:pk>/", views_instrument_folder.create_folder_review, name='folder-create-review'),
    path("create-file-review/<str:pk>/", views_instrument_folder.create_file_review, name='file-create-review'),

    #------------------------------[ URLS FOR EDITING FILES ]------------------------------#

Api/urls.py
from django.urls import path
from Api import views_exhibits, views_fis, views_ris, views_esis, views_student_award
from .views import CreateCategory, FacultyCertificateRecords, ProgramAccreditation, SeminarRecords
from .views_esis import *
from Api import views

app_name = 'apis'

urlpatterns = [
    path('program-accreditation-records/', ProgramAccreditation.as_view(), name='program-accreditaion'),

    path('exhibit/<str:program_accred_pk>/', views_exhibits.landing_page, name='exhibit-page'),
    path('student-awards/<str:program_accred_pk>/', views_student_award.landing_page, name='student-award-page'),

    path('esis/extension/records/<str:program_accred_pk>/', views_esis.extension_info, name='extension-info'),
    path('ris/research/infos/students/<str:program_accred_pk>/', views_ris.research_student, name='research-info-student'),
    path('ris/research/infos/faculties/<str:program_accred_pk>/', views_ris.research_faculty, name='research-info-faculty'),

    path('fis/awards/infos/<str:program_accred_pk>/', views_fis.faculty_awards_info, name='faculty-awards-info'),

    path('faculty/certificate/records/', FacultyCertificateRecords.as_view(), name='faculty-certificate-info'),
    path('faculty/seminars-workshops-trainings/records/', SeminarRecords.as_view(), name='seminars-workshops-trainings'),
    path('faculty/category/records/', CreateCategory.as_view(), name='category'),

    path('faculty-development/data/', views_fis.FacultyDevelopmentAPI.as_view(), name='api-faculty-development')


] 

LandingPage/urls.py
from django.urls import path
# from .views import UserRegistration
from . import views

app_name = 'index'

urlpatterns = [
    # path('', views.index_page, name='index-page'),
    path('about/', views.about_page, name='about-page'),
    path('', views.login_page, name='login-page'),


]

LandingPage/views.py
from django.contrib import messages
from django.shortcuts import redirect, render


def index_page(request):
    return render(request, 'index-page/index.html')

def about_page(request):
    return render(request, 'about/about.html')

def login_page(request):
    return render(request, 'registration/login.html')

Accreditation/templates/accreditation-instrument/archive-page/instrument-cards.html
<div class="row row-cards">

    <!-- For LOOP HERE-->
    {% for record, update_form, created_by, modified_by in details %}

        <div class="col-sm-6 col-lg-4">
            <div class="card" onmouseover="addHoverClass(this)" onmouseout="removeHoverClass(this)">
                <div class="card-status-start bg-red"></div>
      
                    <div class="card-body">
                        <div class="d-flex align-items-center">

                            <div class="subheader">{{ record.accredbodies.abbreviation }}</div>

                            <div class="ms-auto lh-1">
                                
                                <div class="dropdown">
                                    <a class="text-muted" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M12 19m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M12 5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /></svg>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-end">
                                        <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#view-modal-{{ record.id }}">View</button>
                                        <button class="dropdown-item edit-button" data-bs-toggle="modal" data-bs-target="#edit-modal-{{ record.id }}">Edit</button>
                                        <a  href={% url 'accreditations:instrument-restore' pk=record.id %} class="dropdown-item">Restore</a>
                                        <button type="button" class="dropdown-item text-danger delete-button" id="delete-button" data-id={{ record.id }}>Delete</button>

                                    </div>
                                </div>
                            </div>

                        </div>
                        <a href="{% url 'accreditations:instrument-level' pk=record.id %}">
                            <div class="h3 mb-3">{{ record.name }}</div>
                        </a>
                    </div>

            </div>
        </div>


        {% include "accreditation-instrument/archive-page/view_modal.html" %}
        {% include "accreditation-instrument/main-page/edit_modal.html" %}
    {% endfor %}
</div>

Accreditation/templates/accreditation-instrument/archive-page/landing-page.html
{% extends "base.html" %}
<!-- PAGE TITLE FOR THIS PAGE -->
{% block page-title %}
    Archived Accreditation Instruments
{% endblock page-title %}


<!-- ACTION BUTTONS/ELEMENTS INLINE TO THE PAGE TITLE -->
{% block page-title-actions %}
        <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Search instrument..."/>
        <a href="{% url 'accreditations:instrument-list' %}" type="button" class="btn btn-primary">
            <i class="fa-solid fa-arrow-left"></i> Back
        </a>

{% endblock page-title-actions %}

{% block content %}

    {% include "accreditation-instrument/archive-page/instrument-cards.html" %}

    {% include "accreditation-instrument/archive-page/scripts.html" %}
   
{% endblock content %}

Accreditation/templates/accreditation-instrument/archive-page/scripts.html
{% comment %} These are the scripts for the archive landing page. {% endcomment %}

{% comment %} AJAX FOR UPDATING  {% endcomment %}
{% comment %} AJAX FOR UPDATING  {% endcomment %}
<script>
    $(document).ready(function(){
        $(".save-changes").click(function(event) {
            var id = $(this).data('id');
            event.preventDefault();
            event.stopPropagation();
            var serializedData = $("#update-instrument-form-"+id).serialize();
            var url = "/accreditation/instrument/update/"+id+"/";


            $.ajax({
                url: url, 
                data: serializedData,
                headers: { 'X-CSRFToken': '{{ csrf_token }}' }, 
                type: "POST",
                success: function(response) {
                    location.reload();
                    
                },
                error: function(error) {
                    // Check for the errors field in the JSON response
                    if (error.responseJSON && error.responseJSON.errors) {
                        // Iterate over the errors field and display the validation errors to the user
                        for (var field in error.responseJSON.errors) {
                            toastr.error(error.responseJSON.errors[field]);
                        }
                    } else {
                        toastr.error('Something went wrong. Please try again later.');
                    }
                }

            });
        });
    });
</script> 


<script>
	const deleteButtons = document.querySelectorAll('.delete-button');

	deleteButtons.forEach((deleteButton) => {
			deleteButton.addEventListener('click', async () => {
					const id = event.target.dataset.id; // Get the ID of the button
					const { value: password, isConfirmed } = await Swal.fire({
							title: 'Are you sure?',
							text: "All other records related to this program will also be PERMANENTLY deleted.",
							icon: 'warning',
							showCancelButton: true,
							confirmButtonColor: '#3085d6',
							cancelButtonColor: '#d33',
							confirmButtonButtonText: 'Yes, delete it!',
							cancelButtonButtonText: 'No, cancel',
							input: 'password',
							inputPlaceholder: 'Enter your password to confirm deletion',
							inputAttributes: {
									maxlength: 20,
									autocapitalize: 'off',
									autocorrect: 'off'
							}
					});

					if (isConfirmed) 
					{
						if (password) {
								var url = "/accreditation/instrument/archive_page/destroy/"+id+"/";
								// Send AJAX request to verify password
								$.ajax({
										url: url,
										method: 'POST',
										data: { password: password,
												'csrfmiddlewaretoken': '{{ csrf_token }}', },
										success: function(response) {
												if (response.success) {
														window.location.href = response.url_landing;
												} else {
														toastr.error(response.error);
												}
										},
										error: function() {
												toastr.error('Error verifying password');
										}
								});
						} 
						else {
								Swal.fire({
									icon: 'error',
									title: 'Please input a password!',
									showConfirmButton: true,
								});
						}
					}
			});
	});
	 
		
</script>

<script>
    function addHoverClass(card) {
        card.classList.add('card-active');
    }

    function removeHoverClass(card) {
        card.classList.remove('card-active');
    }
</script>

Accreditation/templates/accreditation-instrument/archive-page/view_modal.html
<!-- Modal -->
<div class="modal modal-blur fade" id="view-modal-{{ record.id }}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog ">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">{{ record.name }} Details</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<!-- Label and data from database -->
				<ul class="list-unstyled space-y-3">
					
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Created by</b></div>
							<div class="col-6 text-break ">{{ created_by.first_name }} {{ created_by.last_name }} </div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Created at</b></div>
							<div class="col-6 text-break "> {{record.created_at}} </div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Deleted by</b></div>
							<div class="col-6 text-break "> {{modified_by.first_name}} {{modified_by.last_name}}</div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Deleted at</b></div>
							<div class="col-6 text-break">{{record.deleted_at}}</div>
						</div>
					</li>
					
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Instrument Name</b></div>
							<div class="col-6 text-break">{{ record.name }}</div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Accrediting Body</b></div>
							<div class="col-6  text-break">{{ record.accredbodies.name}} ({{record.accredbodies.abbreviation}}) </div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Program</b></div>
							<div class="col-6  text-break">{{ record.program.program_name}} ({{record.program.abbreviation}}) </div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Instrument Description</b></div>
							<div class="col-6  text-break">{{ record.description }}</div>
						</div>
					</li>

					
				</div>
			</ul>
			<div class="modal-footer">
				<button type="button" class="btn me-auto" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>