ACIS_system_v1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

    path('programs/', include('Programs.urls', namespace='programs')), 
    path('dashboard/', include('Dashboard.urls', namespace='dashboards')),
    path('accreditation/', include('Accreditation.urls', namespace= 'accreditation')),
    path('user/', include('Users.urls', namespace ='users')),

    path('', include('LandingPage.urls', namespace = 'index')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('api/', include('Api.urls', namespace ='apis')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Api/urls.py
from django.urls import path
from Api import views_exhibits, views_fis, views_ris, views_esis, views_student_award
from .views import CreateCategory, FacultyCertificateRecords, ProgramAccreditation, SeminarRecords
from .views_esis import *
from Api import views

app_name = 'apis'

urlpatterns = [
    path('program-accreditation-records/', ProgramAccreditation.as_view(), name='program-accreditaion'),

    path('exhibit/<str:program_accred_pk>/', views_exhibits.landing_page, name='exhibit-page'),
    path('student-awards/<str:program_accred_pk>/', views_student_award.landing_page, name='student-award-page'),

    path('esis/extension/records/<str:program_accred_pk>/', views_esis.extension_info, name='extension-info'),
    path('ris/research/infos/students/<str:program_accred_pk>/', views_ris.research_student, name='research-info-student'),
    path('ris/research/infos/faculties/<str:program_accred_pk>/', views_ris.research_faculty, name='research-info-faculty'),

    path('fis/awards/infos/<str:program_accred_pk>/', views_fis.faculty_awards_info, name='faculty-awards-info'),

    path('faculty/certificate/records/', FacultyCertificateRecords.as_view(), name='faculty-certificate-info'),
    path('faculty/seminars-workshops-trainings/records/', SeminarRecords.as_view(), name='seminars-workshops-trainings'),
    path('faculty/category/records/', CreateCategory.as_view(), name='category'),

    path('faculty-development/data/', views_fis.FacultyDevelopmentAPI.as_view(), name='api-faculty-development')


] 

LandingPage/urls.py
from django.urls import path
# from .views import UserRegistration
from . import views

app_name = 'index'

urlpatterns = [
    # path('', views.index_page, name='index-page'),
    path('about/', views.about_page, name='about-page'),
    path('', views.login_page, name='login-page'),


]

Users/urls.py
from django.urls import path
from Users import views_activities, views_user_groups
# from .views import UserRegistration
from . import views_profile, views_user


app_name = 'users'

urlpatterns = [

    path('logout/user/', views_user.logout_view, name="logout-user"),
    path('', views_user.landing_page, name='landing'),
    path('register/', views_user.register, name="create_user"),
    path('update/<str:pk>/', views_user.update_account, name="update-account"),
    path('deactivate/<str:pk>/', views_user.deactivate_account, name="deactivate-user"),

    path('archive_page/', views_user.archive_landing, name="archive-landing"),
    path('archive_page/restore/<str:pk>/', views_user.reactivate_account, name="restore-user"),

    path('profile/<str:pk>/', views_user.deactivate_account, name="profile-user"),
    path('profile/', views_profile.landing_page, name="profile"),
    path('profile/upload-pic', views_profile.upload_profile_pic, name="profile-upload-pic"),

    path('activities/', views_activities.admin_activities, name="admin-activity-log"),
    path('activities/', views_activities.user_activities, name="user-activity-log"),

    path('groups/', views_user_groups.landing, name="user-groups"),
    path('groups/create/', views_user_groups.CreateUserGroups.as_view(), name="user-groups-create"),
    path('groups/archive/<str:pk>/', views_user_groups.archive, name="user-groups-archive"),
    path('groups/restore/<str:pk>/', views_user_groups.restore, name="user-groups-restore"),
    path('groups/destroy/<str:pk>/', views_user_groups.destroy, name="user-groups-destroy"),
    path('groups/archive-page/', views_user_groups.archive_landing, name="user-groups-archive-page"),


]

Users/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, Group


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, first_name, middle_name , last_name ,password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, first_name, middle_name , last_name ,password, **other_fields)

    def create_user(self, email, first_name, middle_name , last_name ,password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email,
                          first_name=first_name, middle_name=middle_name , last_name=last_name,**other_fields)
        user.set_password(password)
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    middle_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    start_date = models.DateTimeField(default=timezone.now)
    about = models.TextField(_(
        'about'), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    profile_pic = models.ImageField(upload_to='profile_pictures/')
    created_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='created_customuser', null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_customuser', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    deactivated_at = models.DateTimeField(auto_now=False, null=True, blank=True)


    objects = CustomAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'middle_name']

    def __str__(self):
        return self.first_name
    
class CustomUser_profile(models.Model):
    account = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    birth_date = models.DateField(null=True, blank=True)
    religion = models.CharField(max_length=150, blank=True, null=True)
    sex = models.CharField(max_length=6,blank=True, null=True)
    civil_status = models.CharField(max_length=20, blank=True, null=True)
    nationality = models.CharField(max_length=20, blank=True, null=True)
    personal_no = models.CharField(max_length=11, blank=True, null=True)
    contact_no = models.CharField(max_length=11, blank=True, null=True)
    contact_email = models.CharField(max_length=50, blank=True, null=True)
    province = models.CharField(max_length=30, blank=True, null=True)
    city = models.CharField(max_length=30, blank=True, null=True)
    house_no = models.CharField(max_length=30, blank=True, null=True)
    street_address = models.CharField(max_length=30, blank=True, null=True)
    barangay = models.CharField(max_length=30, blank=True, null=True)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_profile', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True, null=True)

class activity_log(models.Model):
    acted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='acted_by', null=True, blank=True)
    module = models.CharField(max_length=250, null=True, blank=True)
    type = models.CharField(max_length=10, null=True, blank=True)
    action = models.CharField(max_length=250, null=True, blank=True)
    datetime_acted = models.DateTimeField(default=timezone.now)
    deleted_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

# For storing the information of the created user groups. We must don't alter the auth_group model. Just add model related to that model
class auth_group_info(models.Model):
    auth_group =  models.OneToOneField(Group, on_delete=models.CASCADE, related_name="auth_group_info")
    created_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='created_group_info')
    created_at = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_group_info', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        unique_together = [("auth_group",)]

    def __str__(self):
        return self.auth_group.name

class faculty_certificates(models.Model):
    first_name = models.CharField(max_length=150, null=False)
    last_name = models.CharField(max_length=150, null=True, blank=True)
    middle_name = models.CharField(max_length=150, null=True, blank=True)
    award_recieved = models.CharField(max_length=200, null=True, blank=True, unique=False)
    certifying_body = models.CharField(max_length=200, null=True, blank=True, unique=False)
    date =  models.DateTimeField(auto_now=False, null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='created_faculty', null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_faculty', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)



class category_training(models.Model):
    name = models.CharField(max_length=20, null=False, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='created_category', null=True, blank=True)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_category', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    

class seminar_workshop_training(models.Model):
    category =  models.ForeignKey(category_training, on_delete=models.CASCADE, related_name="category_relation")
    title = models.CharField(max_length=150, null=False)
    inclusive_date =  models.DateTimeField(auto_now=False, null=True, blank=True)
    classification = models.CharField(max_length=150, null=False)
    sponsoring_agency = models.CharField(max_length=150, null=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='created_seminar', null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    modified_by = models.ForeignKey( settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='modified_seminar', null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

LandingPage/views.py
from django.contrib import messages
from django.shortcuts import redirect, render


def index_page(request):
    return render(request, 'index-page/index.html')

def about_page(request):
    return render(request, 'about/about.html')

def login_page(request):
    return render(request, 'registration/login.html')

Users/templates/deactivated-users/landing_page.html
{% extends 'base.html' %} 

<!-- PAGE TITLE FOR THIS PAGE -->
{% block page-title %}
    User Archive Page
{% endblock page-title %}


<!-- ACTION BUTTONS/ELEMENTS INLINE TO THE PAGE TITLE -->
{% block page-title-actions %}
        <input type="search" class="form-control d-inline-block w-9 me-3" placeholder="Search program…"/>
        {% if perms.Users.delete_customuser %}
            <a href="{% url 'users:landing' %}" type="button" class="btn btn-primary">
                <i class="fa-solid fa-arrow-left"></i> Back
            </a>
            <button type="button" class="btn btn-success" disabled>Restore</button>
        {% endif %}
{% endblock page-title-actions %}


{% block content %}

    {% if perms.Users.delete_customuser %}
        <!-- USER CARDS -->
        {% include "deactivated-users/user_cards.html" %} 

        <!-- STYLES -->
        {% include "deactivated-users/styles.html" %} 

        <!-- SCRIPTS -->
        {% include "deactivated-users/scripts.html" %}
    {% endif %}

{% endblock content %}

Users/templates/deactivated-users/scripts.html
<script>
	const deleteButtons = document.querySelectorAll('.reactivate-button');

	deleteButtons.forEach((deleteButton) => {
			deleteButton.addEventListener('click', async () => {
					const id = event.target.dataset.id; // Get the ID of the button
					const { value: password, isConfirmed } = await Swal.fire({
							title: 'Are you sure?',
							text: "This account will be reactivated and can be used again for logging into the system.",
							icon: 'warning',
							showCancelButton: true,
							confirmButtonColor: '#3085d6',
							cancelButtonColor: '#d33',
							confirmButtonButtonText: 'Yes, delete it!',
							cancelButtonButtonText: 'No, cancel',
							input: 'password',
							inputPlaceholder: 'Enter your password to confirm action',
							inputAttributes: {
									maxlength: 20,
									autocapitalize: 'off',
									autocorrect: 'off'
							}
					});

					if (isConfirmed) 
					{
						if (password) {
								var url = "/user/archive_page/restore/"+id+"/";
								// Send AJAX request to verify password
								$.ajax({
										url: url,
										method: 'POST',
										data: { password: password,
												'csrfmiddlewaretoken': '{{ csrf_token }}', },
										success: function(response) {
												if (response.success) {
														window.location.href = response.url_landing;
												} else {
														toastr.error(response.error);
												}
										},
										error: function() {
												toastr.error('Error verifying password');
										}
								});
						} else {
								Swal.fire({
									icon: 'error',
									title: 'Please input a password!',
									showConfirmButton: true,
								});
						}
				}
			});
	});
	 
		
</script>

Users/templates/deactivated-users/user_cards.html
{% load static %}
<div class="row row-cards">
    {% for record, update_form, created_by, modified_by in details  %}
        <div class="col-md-6 col-lg-3">
            <div class="card card-link-pop">
                <div class="card-status-top bg-red"></div>
                <div class="card-body p-4 text-center">
                    {% if record.profile_pic %}
                        <span class="avatar avatar-xl mb-3 rounded" style="background-image: url(./static/avatars/000m.jpg)"></span>
                    
                    {% else %}
                        <span class="avatar avatar-xl mb-3 rounded">{{ record.first_name|first|default:'' }} {{ record.last_name|first|default:'' }}</span>
                    {% endif %}

                    <h3 class="m-0 mb-1"><a href="#">{{ record.first_name }} {{ record.last_name }} </a></h3>
                    <div class="text-muted">{{ record.email }}</div>
                    <div class="mt-3">
                        <span class="badge bg-green-lt">Admin</span>
                    </div>
                </div>
                <div class="d-flex">
                    <a href="#" class="card-btn" data-bs-toggle="modal" data-bs-target="#view-modal-{{ record.id }}">
                        View
                    </a>

                    {% if perms.Users.change_customuser %}
                        <a href="#" class="card-btn edit-button" data-bs-toggle="modal" data-bs-target="#edit-modal-{{ record.id }}" >
                            Edit
                        </a>
                    {% endif %}

                    <a href="#" class="card-btn text-danger reactivate-button" data-id={{ record.id }}>
                        Reactivate
                    </a>
                </div>
            </div>
        </div>
        {% if perms.Users.change_customuser %}
            {% include "users/edit_modal.html" %} 
        {% endif %}
        
        {% include "deactivated-users/view_modal.html" %} 
    {% endfor %}
</div>

Users/templates/deactivated-users/view_modal.html
  <!-- Modal -->
  <div class="modal modal-blur fade" id="view-modal-{{ record.id }}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog ">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Easy View Account</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<!-- Label and data from database -->
				<ul class="list-unstyled space-y-3">
					
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Created by</b></div>
							<div class="col-6 text-break ">{{ created_by.first_name }} {{ created_by.last_name }} </div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Created at</b></div>
							<div class="col-6 text-break "> {{record.created_at}} </div>
						</div>
					</li>
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Deactivated by</b></div>
							<div class="col-6 text-break "> {{modified_by.first_name}} {{modified_by.last_name}}</div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Date Deactivated</b></div>
							<div class="col-6 text-break">{{record.deactivated_at}}</div>
						</div>
					</li>
					
					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Account Name</b></div>
							<div class="col-6 text-break">{{ record.first_name }} {{ record.middle_name|first|default:'' }}. {{ record.last_name }}</div>
						</div>
					</li>

					<li>
						<div class="row">
							<div class="col-4 offset-1"><b>Account Email</b></div>
							<div class="col-6 text-break ">{{ record.email }}</div>
						</div>
					</li>
				</div>
			</ul>
			<div class="modal-footer">
				<button type="button" class="btn me-auto" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>