ACIS_system_v1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

    path('programs/', include('Programs.urls', namespace='programs')), 
    path('dashboard/', include('Dashboard.urls', namespace='dashboards')),
    path('accreditation/', include('Accreditation.urls', namespace= 'accreditation')),
    path('user/', include('Users.urls', namespace ='users')),

    path('', include('LandingPage.urls', namespace = 'index')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('api/', include('Api.urls', namespace ='apis')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accreditation/urls.py
from django.urls import path
from Accreditation import  views_accreditation, views_accreditation_result, views_assign_user, views_instrument_folder, views_instrument_level, views_reports, views_submission_bin
from . import views_level, views_bodies, views_instrument

from Accreditation.views_instrument_level import *

app_name = 'accreditations'

urlpatterns = [

    #------------------------------[ URLS FOR ACCREDITATION LEVEL MODULE ]------------------------------#
    path("level/", views_level.landing_page, name='level-landing'),
    path("level/create/", views_level.create_level, name='level-create'),
    path("level/update/<str:pk>/", views_level.update_level, name='level-update'),
    path("level/archive/<str:pk>/", views_level.archive_level, name='level-archive'),
    path("level/archive_page/", views_level.archive_level_page, name='level-archive-page'),
    path("level/archive_page/restore/<str:pk>/", views_level.restore_level, name='level-archive-page-restore'),
    path("level/archive_page/destroy/<str:pk>/", views_level.destroy_level, name='level-archive-page-destroy'),

    
    #------------------------------[ URLS FOR ACCREDITATION BODIES MODULE ]------------------------------#
    path("bodies/", views_bodies.landing_page, name='bodies-landing'),
    path("bodies/create/", views_bodies.create_bodies, name='bodies-create'),
    path("bodies/update/<str:pk>/", views_bodies.update_bodies, name='bodies-update'),
    path("bodies/archive/<str:pk>/", views_bodies.archive_bodies, name='bodies-archive'),
    path("bodies/archive_page/", views_bodies.archive_landing, name='bodies-archive-page'),
    path("bodies/archive_page/restore/<str:pk>/", views_bodies.restore_bodies, name='bodies-archive-page-restore'),
    path("bodies/archive_page/destroy/<str:pk>/", views_bodies.destroy_bodies, name='bodies-archive-page-destroy'),
    
    #------------------------------[ URLS FOR INSTRUMENT MODULE]------------------------------#
    path("instrument/", views_instrument.InstrumentList.as_view(), name='instrument-list'),
    path("instrument/update/<str:pk>/", views_instrument.update, name='instrument-update'),
    path("instrument/archive/<str:pk>/", views_instrument.archive, name='instrument-archive'),
    path("instrument/archive_page/", views_instrument.archive_landing, name='instrument-archive-page'),
    path("instrument/archive_page/restore/<str:pk>/", views_instrument.restore, name='instrument-restore'),
    path("instrument/archive_page/destroy/<str:pk>/", views_instrument.destroy, name='instrument-destroy'),

    #------------------------------[ URLS FOR INSTRUMENT LEVEL ]------------------------------#
    path("instrument/level/<str:pk>/", InstrumentLevelList.as_view(), name='instrument-level'),
    path("instrument/level/create/<int:pk>/", InstrumentLevelList.as_view(), name='instrument-level-create'),
    path("instrument/level/update/<str:pk>/", views_instrument_level.update, name='instrument-level-update'),
    path("instrument/level/archive/<str:ins_pk>/<str:pk>/", views_instrument_level.archive, name='instrument-level-archive'),
    path("instrument/level/<str:pk>/archive-page/", views_instrument_level.archive_landing, name='instrument-level-archive-page'),
    path("instrument/level/archive-page/restore/<str:ins_pk>/<str:pk>/", views_instrument_level.restore, name='instrument-level-restore'),
    path("instrument/level/archive-page/destroy/<str:pk>/", views_instrument_level.destroy, name='instrument-level-destroy'),

    #------------------------------[ URLS FOR PARENT FOLDER ]------------------------------#
    path("instrument/level/directory/<str:pk>/", views_instrument_folder.parent_landing_page, name='instrument-level-directory'),
    path("instrument/level/directory/create/<str:pk>/", views_instrument_folder.create, name='instrument-directory-create'),
    path("instrument/level/directory/update/<str:pk>/", views_instrument_folder.update, name='instrument-directory-update'),
    path("instrument/level/directory/archive/<str:pk>/<str:level_id>/", views_instrument_folder.archive, name='instrument-directory-archive'),
    path("instrument/level/parent-directory/file/archive/<str:pk>/", views_instrument_folder.archive_files, name='parent-directory-file-archive'),
    path("instrument/level/parent-directory/recycle-bin/<str:pk>/", views_instrument_folder.parent_recycle_bin, name='parent-folder-recycle-bin'),
    path("instrument/level/parent-directory/recycle-bin/restore/<str:ins_pk>/<str:pk>/", views_instrument_folder.restore_parent, name='parent-directory-recycle-bin-restore'),
    path("instrument/level/parent-directory/recycle-bin/destroy/<str:pk>/", views_instrument_level.destroy, name='parent-directory-recycle-bin-destroy'),
    path("instrument/level/parent-directory/upload-files/<str:pk>/", views_submission_bin.create_parent_folder_files, name='parent-folder-files-upload'),
    path("instrument/level/directory/recycle-bin/destroy/<str:pk>/", views_instrument_folder.destroy, name='folder-destroy'),


    #------------------------------[ URLS FOR CHILD FOLDER ]------------------------------#
    path("instrument/level/child/directory/<str:pk>/", views_instrument_folder.child_landing_page, name='instrument-level-child-directory'),
    path("instrument/level/child/directory/create/<str:pk>/", views_instrument_folder.create_child, name='instrument-directory-create-child'),
    path("instrument/level/child/directory/archive/<str:pk>/<str:parent_id>/", views_instrument_folder.archive_child, name='instrument-directory-archive-child'),
    path("instrument/level/child-directory/recycle-bin/<str:pk>/", views_instrument_folder.child_recycle_bin, name='child-folder-recycle-bin'),
    path("instrument/level/child-directory/recycle-bin/restore/<str:parent_pk>/<str:pk>/", views_instrument_folder.restore_child, name='child-directory-recycle-bin-restore'),
    path("instrument/level/child-directory/recycle-bin/restore-file/<str:pk>/", views_instrument_folder.restore_child_file, name='child-file-restore'),
    path("instrument/level/child-directory/upload-files/<str:pk>/", views_submission_bin.create_child_folder_files, name='child-folder-files-upload'),


    #------------------------------[ URLS FOR SUBMISSION BIN ]------------------------------#
    path("instrument/level/directory/submission-bin/<str:pk>/", views_submission_bin.landing_page, name='submission-bin-page'),
    path("instrument/level/parent-directory/create/submission-bin/<str:pk>/", views_submission_bin.create_submissionBin_parent, name='create-parent-submission-bin'),
    path("instrument/level/child-directory/create/submission-bin/<str:pk>/", views_submission_bin.create_submissionBin_child, name='create-child-submission-bin'),
    path("instrument/level/directory/submission-bin/update/<str:pk>/", views_submission_bin.update, name='instrument-directory-update'),
    path("instrument/level/directory/submission-bin/upload-files/<str:pk>/", views_submission_bin.create_files, name='files-upload'),
    path("instrument/level/directory/submission-bin/archive/<str:pk>/<str:bin_id>/", views_submission_bin.archive, name='file-archive'),
    path("instrument/level/directory/submission-bin/recycle-bin/<str:pk>/", views_submission_bin.recycle_bin, name='submission-bin-recycle-bin-page'),
    path("instrument/level/directory/submission-bin/recycle-bin/restore/<str:pk>/", views_submission_bin.restore, name='file-restore'),
    path("instrument/level/directory/submission-bin/recycle-bin/destroy/<str:pk>/", views_submission_bin.destroy, name='file-destroy'),
    path("submission-bin/file/change/reviewable/<str:pk>/", views_submission_bin.change_to_reviewable_file, name='submission-bin-change-to-reviewable'),
    path("submission-bin/file/change/unreviewable/<str:pk>/", views_submission_bin.change_to_not_reviewable_file, name='submission-bin-change-to-unreviewable'),


    #------------------------------[ URLS FOR PROGRAM ACCREDITATION ]------------------------------#
    path("filter-instrument-option/", views_accreditation.filter_instrument, name='filter-instument-option'),

    path("", views_accreditation.landing_page, name='landing'),
    path("create/", views_accreditation.create, name='accreditation-create'),
    path("update/<str:pk>/", views_accreditation.update, name='accreditation-update'),
    path("archive/<str:pk>/", views_accreditation.archive, name='accreditation-archive'),
    path("archive-page/", views_accreditation.archive_landing, name='accreditation-archive-page'),
    path("archive-page/restore/<str:pk>/", views_accreditation.restore, name='accreditation-restore'),
    path("archive-page/destroy/<str:pk>/", views_accreditation.destroy, name='accreditation-destroy'),


    #------------------------------[ URLS FOR ASSIGNING USER TO A FOLDER ]------------------------------#
    path("directory/assign-user/", views_assign_user.assign_user, name='folder-assign-user'),
    path("directory/assign-user/chairman/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_chairman, name='folder-assign-user-chairman'),   
    path("directory/assign-user/co-chairman/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_cochariman, name='folder-assign-user-cochairman'),
    path("directory/assign-user/member/<str:pk>/<str:folder_pk>/", views_assign_user.change_to_member, name='folder-assign-user-member'),
    path("directory/assign-user/remove-user/<str:pk>/<str:folder_pk>/", views_assign_user.removed_user_to_folder, name='folder-remove-user'),


    #------------------------------[ URLS FOR REVIEWING FILES AND FOLDERS ]------------------------------#
    path("create-review/<str:pk>/", views_instrument_folder.create_folder_review, name='folder-create-review'),
    path("create-file-review/<str:pk>/", views_instrument_folder.create_file_review, name='file-create-review'),

    #------------------------------[ URLS FOR EDITING FILES ]------------------------------#

Api/urls.py
from django.urls import path
from Api import views_exhibits, views_fis, views_ris, views_esis, views_student_award
from .views import CreateCategory, FacultyCertificateRecords, ProgramAccreditation, SeminarRecords
from .views_esis import *
from Api import views

app_name = 'apis'

urlpatterns = [
    path('program-accreditation-records/', ProgramAccreditation.as_view(), name='program-accreditaion'),

    path('exhibit/<str:program_accred_pk>/', views_exhibits.landing_page, name='exhibit-page'),
    path('student-awards/<str:program_accred_pk>/', views_student_award.landing_page, name='student-award-page'),

    path('esis/extension/records/<str:program_accred_pk>/', views_esis.extension_info, name='extension-info'),
    path('ris/research/infos/students/<str:program_accred_pk>/', views_ris.research_student, name='research-info-student'),
    path('ris/research/infos/faculties/<str:program_accred_pk>/', views_ris.research_faculty, name='research-info-faculty'),

    path('fis/awards/infos/<str:program_accred_pk>/', views_fis.faculty_awards_info, name='faculty-awards-info'),

    path('faculty/certificate/records/', FacultyCertificateRecords.as_view(), name='faculty-certificate-info'),
    path('faculty/seminars-workshops-trainings/records/', SeminarRecords.as_view(), name='seminars-workshops-trainings'),
    path('faculty/category/records/', CreateCategory.as_view(), name='category'),

    path('faculty-development/data/', views_fis.FacultyDevelopmentAPI.as_view(), name='api-faculty-development')


] 

Accreditation/templates/accreditation-level-parent-directory/main-page/partials/area-navigation.html
<div class="col-2">
    <div class="row">
        {% if accred_program %}
            <div class="subheader mb-2">Other Modules</div>
            <div class="list-group list-group-transparent mb-2">
                <a class="list-group-item d-flex align-items-center" href="{% url "apis:exhibit-page" program_accred_pk=accred_program.id%}">
                    EXHIBITS
                </a>

                {% if perms.Accreditation.view_accreditation_certificates %}
                    <a class="list-group-item d-flex align-items-center" href="{% url "accreditations:accreditation-result-page" accred_program.id %}">
                        ACCREDITATION RESULT
                    </a>
                {% endif %}
            </div>
        {% endif %}

        <div class="subheader mb-2">INSTRUMENTS</div>
        <div class="list-group list-group-transparent mb-2">

            {% for nav_record in nav_records %}
                {% if nav_record.parent_directory_id == None %}
                    <div class="accordion-item">
                        <div class="row align-items-center">
                            <div class="col-8 text-truncate">
                                <a class="list-group-item d-flex align-items-center" href="{% url 'accreditations:instrument-level-child-directory' pk=nav_record.id %}"
                                    data-bs-toggle="tooltip" 
                                    data-bs-html="true" 
                                    data-bs-placement="bottom"
                                    title="<small>{{  nav_record.name }}: {{ nav_record.label}}</small>">
                                    {{ nav_record.name }}
                                    </a>
                                    
                            </div>

                            <div class="col-4">
                                <button class="navi-button btn-sm btn-action btn rounded-circle btn-icon" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{nav_record.id}}" aria-expanded="true">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-right">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M9 6l6 6l-6 6" />
                                    </svg>
                                </button>
                            </div>
                        </div>

                        <div id="collapse-{{nav_record.id}}" class="accordion-collapse collapse p-0" data-bs-parent="#accordion-example">
                            <div class="accordion-body pt-0 text-truncate">
                                <ul>
                                    {% for child_nav_record in nav_records %}
                                        {% if child_nav_record.parent_directory_id == nav_record.id %}
                                            <li>
                                                <div class="accordion-item">
                                                    <div class="row align-items-center">
                                                        <div class="col-8 text-truncate">
                                                            <a class="small text-black p-2 d-flex align-items-center" href="{% url 'accreditations:instrument-level-child-directory' pk=child_nav_record.id %}"
                                                                data-bs-toggle="tooltip" 
                                                                data-bs-html="true" 
                                                                data-bs-placement="bottom"
                                                                title="<small>{{  child_nav_record.name }}: {{ child_nav_record.label}}</small>">
                                                                {{  child_nav_record.name }}
                                                                </a>
                                                                
                                                        </div>
                                        
                                                        <div class="col-4">
                                                            <button class=" navi-button btn-sm btn-action btn rounded-circle btn-icon" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{child_nav_record.id}}" aria-expanded="true">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline nav-icon icon-tabler-chevron-right">
                                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                    <path d="M9 6l6 6l-6 6" />
                                                                    </svg>
                                                            </button>
                                                        </div>
                                                    </div>
                                                    

                                            
                                                <div id="collapse-{{child_nav_record.id}}" class="accordion-collapse  p-0 collapse" data-bs-parent="#accordion-example">
                                                    <div class="accordion-body pt-0">
                                                        <ul>
                                                            {% for grand_child_nav_record in nav_records %}
                                                                {% if grand_child_nav_record.parent_directory_id == child_nav_record.id %}
                                                                    <li>
                                                                        <a class="small text-black p-2 d-flex align-items-center" href="{% url 'accreditations:instrument-level-child-directory' pk=grand_child_nav_record.id %}"
                                                                            data-bs-toggle="tooltip" 
                                                                            data-bs-html="true" 
                                                                            data-bs-placement="bottom"
                                                                            title="<small>{{  grand_child_nav_record.name }}: {{ grand_child_nav_record.label}}</small>">
                                                                            {{  grand_child_nav_record.name }}
                                                                        </a>
                                                                    </li>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </ul>
                                    
                                                    </div>
                                                </div>
                                                </div>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}


            {% endfor %}

        </div>
    </div>
</div>

Accreditation/templates/accreditation-level-parent-directory/main-page/partials/file-details-modal.html
{% load custom_tags %}
<!-- Modal -->
<div class="modal modal-blur fade" id="view-modal-{{ file.id }}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-xl">
		<div class="modal-content"> 
			<div class="modal-header">
				<h5 class="modal-title">File Details</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row row-cards">

					<div class="card">
						<div class="card-status-top bg-cyan"></div>
						<div class="card-body">
							<h3 class="card-title">Details</h3>
						
							<div class="datagrid">

								<div class="datagrid-item">
									<div class="datagrid-title">File Name</div>
									<div class="datagrid-content">{{ file.file_name }}</div>
								</div>

								<div class="datagrid-item">
									<div class="datagrid-title">Type</div>
									<div class="datagrid-content">
										{% if file.file_name|slice:"-4:" == '.pdf' %}
											<span class="badge">PDF</span>

										{% elif file.file_name|slice:"-4:" == '.doc' or file.file_name|slice:"-4:" == 'docx'%}
											<span class="badge">Google Docs or Microsoft Word</span>

										{% elif file.file_name|slice:"-4:" == '.xls' or file.file_name|slice:"-4:" == 'xlsx'%}
											<span class="badge">Google sheet or Microsoft Excel</span>

										{% elif file.file_name|slice:"-4:" == '.jpg' or file.file_name|slice:"-4:" == 'jpeg' or file.file_name|slice:"-4:" == '.png' %}
									
											<span class="badge">Image</span>

										{% elif file.file_name|slice:"-4:" == '.mp4' or file.file_name|slice:"-4:" == 'webm' %}
											<span class="badge">Video</span>
								
										{% endif %}
									</div>
								</div>

								<div class="datagrid-item">
									<div class="datagrid-title">Size</div>
									<div class="datagrid-content">{{ file.file_path.size|sizify }} </div>
								</div>

								
								<div class="datagrid-item">
									<div class="datagrid-title">Uploaded by</div>
									<div class="datagrid-content">{{file.uploaded_by.first_name}} {{file.uploaded_by.last_name}}</div>
								</div>

								
								<div class="datagrid-item">
									<div class="datagrid-title">Uploaded at</div>
									<div class="datagrid-content">{{file.uploaded_at|date:"F j, Y"}}</div>
								</div>

								<div class="datagrid-item">
									<div class="datagrid-title">Modified by</div>
									<div class="datagrid-content">{{file.modified_by.first_name}} {{file.modified_by.last_name}}</div>
								</div>

								<div class="datagrid-item">
									<div class="datagrid-title">Last Modified</div>
									<div class="datagrid-content">{{file.modified_at|date:"F j, Y"}}</div>
								</div>

							</div>

						</div>
					</div>


					{% if file.can_be_reviewed %}
						<div class="card">
							<div class="card-status-top bg-cyan"></div>
							<div class="card-body">
								<h3 class="card-title">Approval Status</h3>

							{% if file.reviewed_by %}
								<div class="row p-2">
									<div class="col-4 "><b>Reviewed by</b></div>
									<div class="col-6 text-break "> {{ file.reviewed_by.first_name }}  {{ file.reviewed_by.last_name }}
									</div>
								</div>

								<div class="row  p-2">
									<div class="col-4"><b>Review date</b></div>
									<div class="col-6 text-break "> {{ file.reviewed_at }}
									</div>
								</div>
							
							{% endif %}


								<div class="row p-2">
									<div class="col-4"><b>Status</b></div>
									<div class="col-6 text-break ">
										{% if file.can_be_reviewed %}
											<span class="badge badge-outline text-cyan">[{{file.rating}}] - {{ file.status }}</span>
										{% endif %}

									</div>
								</div>

								<div class="row  p-2">
									<div class="col-4"><b>Remarks</b></div>
									<div class="col-6 text-break "> 
										{% if file.remarks %}
											<a href="#"  data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#view-file-remarks-modal-{{file.id}}">Click to view Remarks</a>
										{% else %}
											<p class="text-muted">No remarks</p>
										{% endif %}
									</div>
								</div>

							</div>
						</div>
					{% endif %}
					

				</div>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn me-auto" data-bs-dismiss="modal">Close</button>
			</div>

		</div>
	</div>
</div>

Accreditation/templates/accreditation-level-parent-directory/main-page/partials/view-file-remarks-modal.html
{% load custom_tags %}
<!-- Modal -->
<div class="modal modal-blur fade" id="view-file-remarks-modal-{{file.id}}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content"> 
			<div class="modal-header">
				<h5 class="modal-title">Reviewer Remarks</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row">
						<div class="small text-muted">Reviewer</div>
						<div>{{file.reviewed_by.first_name }} {{file.reviewed_by.last_name }} 
							<small>({{file.reviewed_by.email }})</small>
						</div>
				</div>

				<br>

				<div class="row">
					<div class="small text-muted">Date Reviewed</div>
					<div>{{file.reviewed_at|date:"F j, Y g:i A" }}</div> 
				</div>

				<br>

				<div class="row">
					<div class="text-muted">Remarks</div>
					<div class="px-4">{{file.remarks|safe }}
						
					</div>

				</div>

					
			</div>
	
			<div class="modal-footer">
				<button type="button" class="btn me-auto" data-bs-dismiss="modal"  data-bs-toggle="modal" data-bs-target="#view-modal-{{ file.id }}">Back</button>
			</div>
		</div>
	</div>
</div>

Accreditation/templates/accreditation-level-parent-directory/main-page/partials/view-remarks-modal.html
{% load custom_tags %}
<!-- Modal -->
<div class="modal modal-blur fade" id="view-remarks-modal-{{ record.id }}" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content"> 
			<div class="modal-header">
				<h5 class="modal-title">Reviewer Remarks</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row">
						<div class="small text-muted">Reviewer</div>
						<div>{{ record.reviewed_by.first_name }} {{ record.reviewed_by.last_name }} 
							<small>({{ record.reviewed_by.email }})</small>
						</div>
				</div>

				<br>

				<div class="row">
					<div class="small text-muted">Date Reviewed</div>
					<div>{{ record.reviewed_at|date:"F j, Y g:i A" }}</div> 
				</div> 
				
				

				<br>

				<div class="row">
					<div class="text-muted">Remarks</div>
					<div class="px-4">{{ record.remarks|safe }}
						
					</div>

				</div>

					
			</div>
	
			<div class="modal-footer">
				<button type="button" class="btn me-auto" data-bs-dismiss="modal" 
					data-bs-toggle="modal" 
					data-bs-target="#view-modal-{{ record.id }}">Back
				</button>
			</div>
		</div>
	</div>
</div>